# config.yaml

evaluation:
  output:
    logs: "./logs/"
    reports: "./reports/"

  runs:
    # Evaluation for OpenAI GPT-OSS 120B
    openai-gpt-oss-120B:
      model: openrouter/openai/gpt-oss-120b
      json: true
      evals:
        # Spider diagram:
        # programming
        - humaneval
        # math
        - math_500
        # art
        - mmmu_art
        # biology
        - mmmu_biology
        # chemistry
        - mmmu_chemistry
        # electronics
        - mmmu_electronics
        # mechanical engineering
        - mmmu_mechanical_engineering
        # music
        - mmmu_music
        # cybersecurity
        - cti_bench

    # # Evaluation for OpenAI GPT-OSS 20B
    # openai-gpt-oss-20B:
    #   model: openrouter/openai/gpt-oss-20b
    #   json: true
    #   evals:
    #     - humaneval
    #     - math_500
    #     - mmmu_art
    #     - mmmu_biology
    #     - mmmu_chemistry
    #     - mmmu_electronics
    #     - mmmu_mechanical_engineering
    #     - mmmu_music
    #     - cti_bench

    # # Evaluation for Qwen 3 (30B)
    # openrouter-qwen3-30b:
    #   model: openrouter/qwen/qwen3-30b-a3b-instruct-2507
    #   json: true
    #   evals:
    #     - humaneval
    #     - math_500
    #     - mmmu_art
    #     - mmmu_biology
    #     - mmmu_chemistry
    #     - mmmu_electronics
    #     - mmmu_mechanical_engineering
    #     - mmmu_music
    #     - cti_bench
