# config.yaml

evaluation:
  output:
    logs: "./logs/"
    reports: "./reports/"

  runs:
    # Evaluation for OpenAI GPT-OSS 120B
    openai-gpt-oss-120B:
      model: openrouter/openai/gpt-oss-120b
      json: true
      evals:
        # Spider diagram:
        # reading comprehension
        # - drop # 9536 samples
        # - detailbench
        # # math
        - math_500
        # science
        - openbookqa
        # cybersecurity
        - cti_bench
        - cti_bench_ate
        - cti_bench_mcq
        - cti_bench_rcm
        - cti_bench_vsp

    # Evaluation for OpenAI GPT-OSS 20B
    openai-gpt-oss-20B:
      model: openrouter/openai/gpt-oss-20b
      json: true
      evals:
        # - drop
        # - detailbench
        - math_500
        - openbookqa
        - cti_bench
        - cti_bench_ate
        - cti_bench_mcq
        - cti_bench_rcm
        - cti_bench_vsp

    # Evaluation for Qwen3 A22B (235B)
    openrouter-qwen3-a22b-235b:
      model: openrouter/qwen/qwen3-235b-a22b
      json: true
      evals:
        # - drop
        # - detailbench
        - math_500
        - openbookqa
        - cti_bench
        - cti_bench_ate
        - cti_bench_mcq
        - cti_bench_rcm
        - cti_bench_vsp

    # Evaluation for Kimi K2 (32B)
    openrouter-kimi-k2-32b:
      model: openrouter/moonshotai/kimi-k2
      json: true
      evals:
        # - drop
        # - detailbench
        - math_500
        - openbookqa
        - cti_bench
        - cti_bench_ate
        - cti_bench_mcq
        - cti_bench_rcm
        - cti_bench_vsp

    # Evaluation for Meta LLAMA 4 Maverick (17B)
    openrouter-meta-llama4-maverick-17b:
      model: openrouter/meta-llama/llama-4-maverick
      json: true
      evals:
        # - drop
        # - detailbench
        - math_500
        - openbookqa
        - cti_bench
        - cti_bench_ate
        - cti_bench_mcq
        - cti_bench_rcm
        - cti_bench_vsp

    # Evaluation for Deepseek R1 0528 (671B)
    openrouter-deepseek-r1-0528-671b:
      model: openrouter/deepseek/deepseek-r1-0528
      json: true
      evals:
        # - drop
        # - detailbench
        - math_500
        - openbookqa
        - cti_bench
        - cti_bench_ate
        - cti_bench_mcq
        - cti_bench_rcm
        - cti_bench_vsp
