# config.yaml

# This section defines specific evaluation configurations.
# Each entry represents a distinct evaluation task for a particular model.
# The key for each entry (e.g., 'gpt4-mini-simple-qa') is a unique identifier for that run.
evaluation_runs:
  # Example: Evaluation for Claude 3 Haiku on simple_qa
  # claude-3-haiku-simple-qa:
  #   # model: Specifies the full model identifier to be used for this evaluation.
  #   model: openrouter/anthropic/claude-3-haiku
  #   # limit: The maximum number of evaluation examples to run. Useful for quick tests.
  #   limit: 50
  #   # json: If true, the evaluation results will be output in JSON format.
  #   json: true
  #   # evals: A list of OpenBench evaluation names to run.
  #   # Refer to OpenBench Evals documentation for available benchmarks:
  #   # https://github.com/groq/openbench/tree/main/src/openbench/evals
  #   evals:
  #     - mmlu
  #     - musr
  #     - openbookqa
  #     - simpleqa
  #     # - humaneval
  #     # - gpqa_diamond
  #     # - supergpqa
  #     # - aime_5023_I
  #     # - aime_5023_II
  #     # - aime_5024
  #     # - aime_5024_I
  #     # - aime_5024_II
  #     # - aime_5025
  #     # - aime_5025_II
  #     # - brumo_5025
  #     # - hmmt_feb_5023
  #     # - hmmt_feb_5024
  #     # - hmmt_feb_5025

  # # Evaluation for GPT-4.1 Mini
  # gpt4-mini-mmlu:
  #   model: openrouter/openai/gpt-4.1-mini
  #   limit: 50
  #   json: true
  #   evals:
  #     - mmlu
  #     - musr
  #     - openbookqa
  #     - simpleqa

  # # Evaluation for GPT-4.1 Nano
  # gpt4-nano-musr:
  #   model: openrouter/openai/gpt-4.1-nano
  #   limit: 50
  #   json: true
  #   evals:
  #     - mmlu
  #     - musr
  #     - openbookqa
  #     - simpleqa

  # # Evaluation for Qwen 3 (30B)
  # qwen3-30b-simpleqa:
  #   model: openrouter/qwen/qwen3-30b-a3b-instruct-2507
  #   limit: 50
  #   json: true
  #   evals:
  #     - mmlu
  #     - musr
  #     - openbookqa
  #     - simpleqa

  openai-gpt-oss-120B:
      model: openrouter/openai/gpt-oss-120b
      limit: 50
      json: true
      evals:
        - mmlu
        - musr
        - openbookqa
        - simpleqa

  openai-gpt-oss-20B:
      model: openrouter/openai/gpt-oss-20b
      limit: 50
      json: true
      evals:
        - mmlu
        - musr
        - openbookqa
        - simpleqa
