# config.yaml

evaluation:
  output:
    logs: "./logs/"
    reports: "./reports/"

  runs:
    # Evaluation for OpenAI GPT-OSS 120B
    openai-gpt-oss-120B:
      model: openrouter/openai/gpt-oss-120b
      json: true
      evals:
        # Spider diagram:
        # reading comprehension
        - drop
        # # math
        # - math_500
        # science
        - openbookqa
        # cybersecurity
        - cti_bench_ate
        - cti_bench_mcq
        - cti_bench_rcm
        - cti_bench_vsp

    # # Evaluation for OpenAI GPT-OSS 20B
    # openai-gpt-oss-20B:
    #   model: openrouter/openai/gpt-oss-20b
    #   json: true
    #   evals:
    #     - drop
    #     - math_500
    #     - openbookqa
    #     - cti_bench_ate
    #     - cti_bench_mcq
    #     - cti_bench_rcm
    #     - cti_bench_vsp

    # # Evaluation for Qwen 3 (30B)
    # openrouter-qwen3-30b:
    #   model: openrouter/qwen/qwen3-30b-a3b-instruct-2507
    #   json: true
    #   evals:
    #     - drop
    #     - math_500
    #     - openbookqa
    #     - cti_bench_ate
    #     - cti_bench_mcq
    #     - cti_bench_rcm
    #     - cti_bench_vsp
