# config.yaml

evaluation:
  output:
    logs: "./logs/"
    reports: "./reports/"

  runs:
    # Evaluation for OpenAI GPT-OSS 120B
    openai-gpt-oss-120B:
      model: openrouter/openai/gpt-oss-120b
      # limit: 50
      json: true
      evals:
        # Spider diagram:
        # programming
        - humaneval
        # math
        - math_500
        # art
        - mmmu_art
        # biology
        - mmmu_biology
        # chemistry
        - mmmu_chemistry
        # electronics
        - mmmu_electronics
        # mechanical engineering
        - mmmu_mechanical_engineering
        # music
        - mmmu_music
        # cybersecurity
        - cti_bench



    # Evaluation for OpenAI GPT-OSS 20B
    # openai-gpt-oss-20B:
    #   model: openrouter/openai/gpt-oss-20b
    #   limit: 50
    #   json: true
    #   evals:
    #     - mmlu
    #     - musr
    #     - openbookqa
    #     - simpleqa

    # # Evaluation for Qwen 3 (30B)
    # openrouter-qwen3-30b:
    #   model: openrouter/qwen/qwen3-30b-a3b-instruct-2507
    #   limit: 50
    #   json: true
    #   evals:
    #     - mmlu
    #     - musr
    #     - openbookqa
    #     # Keeps failing because of the "Best VTuber Streamer" question.
    #     # - simpleqa

    # # Evaluation for GPT-4.1 Nano
    # openrouter-gpt4-nano:
    #   model: openrouter/openai/gpt-4.1-nano
    #   limit: 50
    #   json: true
    #   evals:
    #     - mmlu
    #     - musr
    #     - openbookqa
    #     - simpleqa

    # # Evaluation for OpenAI GPT-4.1 Mini
    # openai-o3:
    #   model: openrouter/openai/o3
    #   limit: 50
    #   json: true
    #   evals:
    #     - mmlu
    #     - musr
    #     - openbookqa
    #     - simpleqa

    # # Evaluation for OpenAI O4 Mini
    # openai-o4-mini:
    #   model: openrouter/openai/o4-mini
    #   limit: 50
    #   json: true
    #   evals:
    #     - mmlu
    #     - musr
    #     - openbookqa
    #     - simpleqa

    # # Evaluation for Anthropic Claude Opus 4.1
    # anthropic-claude-opus-4.1:
    #   model: openrouter/anthropic/claude-opus-4.1
    #   limit: 50
    #   json: true
    #   evals:
    #     - mmlu
    #     - musr
    #     - openbookqa
    #     - simpleqa

    # # Evaluation for Anthropic Claude Sonnet 4
    # anthropic-claude-sonnet-4:
    #   model: openrouter/anthropic/claude-sonnet-4
    #   limit: 50
    #   json: true
    #   evals:
    #     - mmlu
    #     - musr
    #     - openbookqa
    #     - simpleqa
