name: Model Evaluation CI/CD

on:
  schedule:
    - cron: '0 0 * * *' # Runs daily at midnight UTC (1 PM PDT)
  workflow_dispatch:      # Allows manual triggering

jobs:
  evaluate-models:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run model evaluation
        id: eval
        env:
          OPENROUTER_API_KEY: ${{ secrets.OPENROUTER_API_KEY }}
        run: |
            bench eval \
              mmlu \
              --model openrouter/moonshotai/kimi-k2 \
              --limit 10 \
              --logfile results_moonshotai_kimi_k2_$(date +%Y%m%d_%H%M) \
              --json
            
            echo "push=true" >> $GITHUB_OUTPUT

      - name: Push changes
        if: steps.eval.outputs.push == 'true'
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

          git add logs/

          if git diff --cached --exit-code; then
            echo "No changes to commit. Exiting."
          else
            git commit -m "Automated: Add new model evaluation results"
            
            git push
          fi

    #   - name: Generate report
    #     run: |
    #       python report_generator.py results.json --output docs/index.html

    #   - name: Deploy to GitHub Pages
    #     uses: peaceiris/actions-gh-pages@v3
    #     with:
    #       github_token: ${{ secrets.GITHUB_TOKEN }}
    #       publish_dir: ./docs
